version: '2'

networks:
  mongodb_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.213.0/24
          gateway: 192.168.213.1
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - mongodb_net
    hostname: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    networks:
      - mongodb_net
    ports:
      - "8082:3000"
    
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    restart: always
    networks:
      - mongodb_net

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
    restart: always
    networks:
      - mongodb_net

  fakesmtp:
    image: munkyboy/fakesmtp
    volumes:
      - ./mail:/var/mail:rw
    ports:
      - "8025:25"
    restart: always
    networks:
      - mongodb_net