version: '2'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    restart: always

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    restart: always

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
    restart: always

  fakesmtp:
    image: munkyboy/fakesmtp
    volumes:
      - ./mail:/var/mail:rw
    ports:
      - "8025:25"
    restart: always