version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.Dockerfile
    volumes:
      - ./app:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    volumes:
      - ./app:/var/www
    links:
      - cache
      - database
      - fakesmtp
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=cache"

  database:
    image: mysql:5.7
    volumes:
      - ./data/database:/var/lib/mysql
    command: --sql_mode=""
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somethingbetter
      - MYSQL_DATABASE=pokemeapp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    depends_on:
      - database
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOSTS: database
    
  cache:
    image: redis:2.8
    ports:
      - "6379:6379"
    restart: always

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host cache
    links:
      - cache
    ports:
      - "8081:8081"
    restart: always

  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - "8083:80"
      - "8025:25"
    restart: always