version: '2'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - ./data/database:/var/lib/mysql
    command: --sql_mode=""
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somethingbetter
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOSTS: mysql
    
  redis:
    image: redis:2.8
    ports:
      - "6379:6379"
    restart: always

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis:redis
    ports:
      - "8081:8081"
    restart: always

  fakesmtp:
    image: munkyboy/fakesmtp
    volumes:
      - ./mail:/var/mail:rw
    ports:
      - "8025:25"
    restart: always