version: '2'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    networks:
      static-network:
        ipv4_address: 172.30.128.1

  redis:
    image: redis:2.8
    restart: always
    ports:
      - "6379"
    networks:
      static-network:
        ipv4_address: 172.30.128.2

  redisCommander:
    image: tenstartups/redis-commander
    restart: always
    command: --redis-host redis
    links:
      - redis:redis
    networks:
      static-network:
        ipv4_address: 172.30.128.3

  fakesmtp:
    image: munkyboy/fakesmtp
    restart: always
    volumes:
      - ./mail:/var/mail:rw
    networks:
      static-network:
        ipv4_address: 172.30.128.4

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.128.0/24