version: '2'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  redis:
    image: redis:2.8
    restart: always
    ports:
      - "6379:6379"

  redisCommander:
    image: tenstartups/redis-commander
    restart: always
    command: --redis-host redis
    links:
      - redis:redis

  fakesmtp:
    image: munkyboy/fakesmtp
    restart: always
    volumes:
      - ./mail:/var/mail:rw